print("A \"quoted\" String is")
print("'much' better if you learn")
print('the rules of "escape sequences."')
print('Also, "" represents an empty String.')
print('Don\'t forget: use \\" instead of " !')
print("\'' is not the same as \"")
